version: '3.4'

services:
  transmission-cleanup:
    image: sethyx/transmission-cleanup:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "TRANSMISSION_RPC=HOST:PORT"
      - "RUN_INTERVAL_MINS=60"
      - "SEEDING_THRESHOLD_HOURS=48"